server:
  port: 8080

spring:
  application:
    name: security-service
  security:
     oauth2:
        client:
           registration:
               google:
                 client-id: 733478155573-g9ogkbgu2hf30uiengk7spgrf7ufv31v.apps.googleusercontent.com
                 #client-id: 733478155573-8ifcsu6uu38i2nu8oloreqgpeng8h8a4.apps.googleusercontent.com
                 client-secret: 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
                 redirect-uri: http://localhost:8080/login/oauth2/code/google






